### ISSUE TITLE
how can I update my themes

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/cinnamon-spices-themes#183]
I want to update my Ubuntu-touch theme on spices but I don't know how. Can you upload this for me?
 here is my new theme  https://www.opendesktop.org/s/Cinnamon/p/1012724/

**Comment by Elbullazul** [comment]
@freemangilgamesh steps on how to do it:

1) fork this repo
2) set up a local copy of your repo (git init, git remote add origin <repo URL>, git remote add upstream https://github.com/linuxmint/cinnamon-spices-themes.git, git pull)
3) paste your theme folder there
4) push changes to your fork (git add --all, git commit -m '<YOURMESSAGEHERE'>, git push)
5) submit a pull request after. Click on pull request in this repo, click new pull request and click on 'compare across forks'. Select your fork and submit a new pull request.
6) When changes are made on this repo you can run git pull upstream to get them on your copy of the repo

cheers!

(nice theme BTW)

**Comment by NikoKrause** [comment]
https://github.com/linuxmint/cinnamon-spices-themes/issues/4

**Comment by brownsr** [comment]
hi @freemangilgamesh  I should have some free time next week to help you load this up if git is not your thing.  There's a few things you can do first though.  If you could please take a look at the readme at the first page of this git repository.  There's a long descriptive section there, and the bit about the file structure is very relevant - this theme has the necessary files to load up into Cinnamon, but it does not have the info, screenshot etc. that are needed to load up into the spices website https://cinnamon-spices.linuxmint.com

I can also see that the theme needs some work for vertical panels.  Perhaps you could see if you could sort that out before we load it up?  I can obviously help, but I'd prefer your theme to be pretty much there first, otherwise there's bound to be rework the next time you update it.  You can look at other themes for examples, they are all pretty similar in the CSS they need to look right in vertical panels.

Of course if you are nifty with git then do please load things up for yourself in the standard file format and submit a git PR, and one of us will review and merge.  Elbullazul has posted some tips above, and I put some more tips on that first page at the start of this repository https://github.com/linuxmint/cinnamon-spices-themes in the readme.

Regards

Simon

**Comment by freemangilgamesh** [comment]
thanks bro! can you upload this too please https://www.opendesktop.org/s/Cinnamon/p/1181352/

**Comment by brownsr** [comment]
OK @freemangilgamesh , both done.  I made a couple of minor changes to fix some alignment problems that would have been apparent.  These should be clear from the commit history if you want to retrofit these.  Hope all is as you expect.  

Regards.  
Simon

**Comment by freemangilgamesh** [comment]
Many thanks bro these look great and feel free to edit any part of them the way you want! cheeeeeeers
