### ISSUE TITLE
Adapta-Nokto

### ISSUE THREAD

**Issue by fbm224** [linuxmint/cinnamon-spices-themes#499]
Ver.  1542521204
Cinnamon 3.8.9
Mint 19
Nvidia
Hi, 

![vera](https://user-images.githubusercontent.com/17212121/49392062-f2c02f80-f6f2-11e8-8d57-625c30a3fff2.png)

Text box is too small, only found  to occur in Veracrypt, it does not occur with other themes like cinnamox:

![vera2](https://user-images.githubusercontent.com/17212121/49392150-36b33480-f6f3-11e8-8b8e-8ef7e4f03ad4.png)

Changing font size, type, or scale does not correct the issue. 

Please let me know if you need something else to debug.
Thank you.

**Comment by smurphos** [comment]
Thanks for the report - it looks like the text is clipping a little in Cinnamox as-well though. What distro are you using and what version of veracrypt?

**Comment by fbm224** [comment]
Cinnamon 3.8.9
Linux Mint 19
Veracrypt 1.22

**Comment by smurphos** [comment]
Are you on a HIDPI screen resolution? It looks from your screenshots you are using the HIDPI variant of the Cinnamox GTK2 theme (the slight clipping in the text in the buttons on veracrypt only occurs on the HIDPI variant for me)

I can reproduce the button issue in Veracrypt with Adapta-Nokto - it's OK with Adapta-Nokto-Eta.

**Comment by fbm224** [comment]
On system configuration -> General -> Desktop scale, I'm using the "auto" setting, which behaves just like the "normal", not the "double HI-DPI"

Adapta-Nokto-Eta still shows the clipping, but less. 

![captura de pantalla de 2018-12-05 10-33-56](https://user-images.githubusercontent.com/17212121/49528310-56746500-f879-11e8-84cb-5c9639883021.png)

**Comment by smurphos** [comment]
It's a veracrypt and/or GTK2 wxWidget bug (more likely the latter)- not a bug in Adapta. The text clipping occurs in all themes (including Adwaita) if the system font-size is set big enough because the buttons fail to expand to fit their contents. It's just more apparent in Adapta due to Adapta's particular styling for it's buttons.

Doesn't occur in Arch based distros - they patch and build veracrypt against GTK3 rather than GTK2 and it looks fine in that environment. I'm not aware of anyone distributing veracrypt for Ubuntu/Debian built against GTK3 but you can self compile.
